### ISSUE TITLE
how to add controls like year effect by gender when doing FE with controls?

### ISSUE THREAD

**Issue by lizhangecon** [tlamadon/pytwoway#46]

**Comment by adamoppenheimer** [comment]
If you are using year effects as a categorical control, then you can simply construct a new column manually. As an example, if you have the columns `t` for years (since bipartitepandas does not treat the time column as categorical, you will have to construct a new column that is categorical in order for this to work properly) and `gender` for genders, and have `n_years` and `n_genders` (=2), then you can construct the interacted column as `n_genders` * `t` + `gender`, or alternatively as `n_years` * `gender` + `t`.

On the other hand, if you want year effects as a continuous variable, unfortunately that is not yet feasible. I already have https://github.com/tlamadon/pytwoway/issues/25 open about it.

Please let me know if this answers your question, and please feel free to ask any other questions you may have!

**Comment by adamoppenheimer** [comment]
Your response:

Thanks for your help. However, when I try to add the categorical controls as stated, the following issue occurs:
```
ValueError('column index exceeds matrix dimensions')
```
Do you have any idea?
I've opened a new issue about this problem, so you can reply there. Thanks

**Comment by adamoppenheimer** [comment]
I have a feeling this has to do with properly adding categorical columns to the BipartitePandas dataframe. Please check out [this page](https://tlamadon.github.io/bipartitepandas/notebooks/custom_columns.html#Adding-custom-columns-to-an-instantiated-DataFrame).

If that doesn't help resolve this, could you please submit a minimal working example of this issue using simulated data?

**Comment by adamoppenheimer** [comment]
Hi @lizhangecon, just following up on this. Were you able to get the code to work?

**Comment by lizhangecon** [comment]
@adamoppenheimer, thanks for your help. In the first place, I tried to construct the columns as suggested in my own dataset before converting it into a BipartitePandas DataFrame:
```
sim_data = pd.read_csv('XXX.txt')
sim_data['int1'] = sim_data['t'] * (sim_data['gender'] + 1)
sim_data['interaction'] = pd.Categorical(sim_data['int1'])
# Convert into BipartitePandas DataFrame
bdf = bpd.BipartiteDataFrame(sim_data,track_id_changes=True)
```
Then, I encountered the 'column index exceeds matrix dimensions' error.
Following your suggestion, I tried the following:
```
sim_data = pd.read_csv('XXX.txt')
sim_data['int1'] = sim_data['t'] * (sim_data['gender'] + 1)
# Convert into BipartitePandas DataFrame
bdf = bpd.BipartiteDataFrame(sim_data,track_id_changes=True)
bdf = bdf.add_column('interaction', sim_data['int1'], is_categorical=True, dtype='categorical')
```
Then, it keeps warning that
```
PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frame.loc[:, subcol] = col_data_lst[i]
```
And the program ends itself because of being out of memory.

**Comment by adamoppenheimer** [comment]
Please try this code:

```python
import numpy as np
import bipartitepandas as bpd

## Simulate data (with gender) ##
rng = np.random.default_rng(1234)
df = bpd.SimBipartite().simulate()
gender = np.array(['m', 'f'])[rng.integers(0, 2, df['i'].nunique())]
df['gender'] = gender[df['i']]

## Create interaction ##
df['interaction'] = df['t'].astype('str') + df['gender']

## Convert into BipartitePandas DataFrame ##
bdf = bpd.BipartiteDataFrame(df[['i', 'j', 'y', 't', 'gender', 'interaction']],
    custom_categorical_dict={'gender': True, 'interaction': True},
    custom_dtype_dict={'gender': 'categorical', 'interaction': 'categorical'},
    custom_how_collapse_dict={'gender': 'first', 'interaction': 'first'},
    track_id_changes=True)
```

Just be careful that the `interaction` column you generate is creating a different value for every possible combination! You don't want to accidentally have multiple groups have the same id. That's why I converted gender into a string representation, so that the `interaction` column becomes for example `1f` or `4m`, which will always be unique.

**Comment by lizhangecon** [comment]
@adamoppenheimer Yes it works! Thanks a lot for your help.
